spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm
    driverClassName: com.mysql.cj.jdbc.Driver
    username: crm_services
    password: AnoirEzzaher10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

